### PR TITLE
Add retry mechanism for openai API calls

### LINKED ISSUE #115: Add retry mechanism for OpenAI API calls
API calls fail more often than they should; we should add a retry mechanism.

### PR DESCRIPTION
**Pull request by harshkumarchourasia**
Add retrying mechanism for openai api calls. 

Sample use cases
1. `complete = models.text_completion.openai("text-davinci-003", **{"wait_exponential_multiplier":1000, "wait_exponential_max":10000, "stop_max_attempt_number":5})`
2. `complete = models.text_completion.openai("text-davinci-003", **{"wait_random_min":1000, "wait_random_max":10000, "stop_max_attempt_number":5})`

Closes #115

### CODE REVIEW

**Review by brandonwillard — CHANGES_REQUESTED** [review]
Don't forget to set up `pre-commit` locally.  Also, `retrying` needs to be added to the `dependencies` in `pyproject.toml`.

**Comment by arunpatro** [comment]
I would advise using https://pypi.org/project/backoff/ instead of retying. Backoff seems to have more stars, and I have seen multiple people using it like the official tree-of-thoughts too

**Comment by brandonwillard** [comment]
> I would advise using https://pypi.org/project/backoff/ instead of retying. Backoff seems to have more stars, and I have seen multiple people using it like the official tree-of-thoughts too
> 
> See: https://github.com/ysymyth/tree-of-thought-llm/blob/9f0f986dc30604b83f8d07203cf09b745ada36aa/models.py#L18

Is there a technical/functional/support reason one of these libraries should be used over the other?

**Comment by arunpatro** [comment]
Nothing too technical as of my current knowledge. Just some thoughts based on seeing various implementations of `retrying`. I found another simple and intuitive library - https://github.com/invl/retry (600 stars).  One reason to prefer this one or backoff (2000 stars) is that `retrying` has only 29 stars. 

I feel using backoff or `retry` can create a more intuitive api extension, I can also try creating a PR to compare.

**Comment by brandonwillard** [comment]
> Nothing too technical as of my current knowledge. Just some thoughts based on seeing various implementations of `retrying`. I found another simple and intuitive library - https://github.com/invl/retry (600 stars). One reason to prefer this one or backoff (2000 stars) is that `retrying` has only 29 stars.
> 
> I feel using backoff or `retry` can create a more intuitive api extension, I can also try creating a PR to compare.

Assuming stars as a proxy for something like quality or maturity of the libraries, and that the changes are trivial, they might as well be made here.

**Comment by rlouf** [comment]
I've always thought [tenacity](https://github.com/jd/tenacity) (a fork of `retrying`) was the de facto standard for this, and it seems to be very similar to `backoff`. If there is a technical reason to prefer `backoff`, let's use that. Otherwise we can stick with `tenacity`.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
