### PR TITLE
Add coverage checks to CI

### LINKED ISSUE #123: Add coverage to CI
The CI checks are missing coverage.  

[This approach](https://hynek.me/articles/ditch-codecov-python/) works without the need for an external service.

### PR DESCRIPTION
**Pull request by brandonwillard**
Closes #123

### CODE REVIEW

**Comment by brandonwillard** [comment]
@rlouf, looks like we're seeing an issue with HF code: [here](https://github.com/normal-computing/outlines/actions/runs/5314761295/jobs/9622336419?pr=149#step:5:41).

**Comment by brandonwillard** [comment]
@rlouf, OK, this seems to work: https://github.com/normal-computing/outlines/actions/runs/5325109338#summary-14415152531

Looks like we might want to go with our old `diff-cover` approach if we want _relative_ coverage requirements, though.

**Review by rlouf — APPROVED** [review]
Looks good to me. The lack of diff is annoying, but not as annoying as CodeCov's random failures. We can always add that later.

**Comment by brandonwillard** [comment]
Just changed it to use `diff-cover` and produce Markdown reports (see [the summary](https://github.com/normal-computing/outlines/actions/runs/5336935769/attempts/1#summary-14446167441)).  I'll push a temporary change in a second and make sure it looks good.

**Comment by brandonwillard** [comment]
@rlouf, how does [this summary](https://github.com/normal-computing/outlines/actions/runs/5337449564/attempts/1#summary-14447692491) look?

**Comment by rlouf** [comment]
Looks pretty good!

**Pull request merged**
